[package]
name = "terminal-ui"
version = "0.1.0"
authors = ["junknet <beini87@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui="0.13"
termion = "1.5.5"
anyhow="1.0"
rand = "0.7"
argh = "0.1"